{{- if ne .Values.kind "CronJob" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "microservices.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "stable" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if .Values.ports }}
            {{- range .Values.ports }}
            - name: {{ .name | default "http" }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
            {{- else }}
            - name: http
              containerPort: {{ .Values.service.port | default 8080 }}
              protocol: TCP
            {{- end }}
          {{- if (or .Values.livenessProbe.enabled (not (hasKey .Values.livenessProbe "enabled"))) }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/healthz" }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 15 }}
          {{- end }}
          {{- if (or .Values.readinessProbe.enabled (not (hasKey .Values.readinessProbe "enabled"))) }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/healthz" }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 3 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
