apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-kv-sync
spec:
  provider: azure
  secretObjects: # This part syncs the KV secret to a standard K8s Secret
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: postgres-password # Name in Key Vault
          key: POSTGRES_PASSWORD      # Key in K8s Secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # Leave empty to use the system-assigned identity of the CSI driver
    keyvaultName: "kv-disasterreliefdev" # This must match your Terraform output
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
    tenantId: "4db0fb37-506e-4401-8aa4-752ee1d1732d"
