apiVersion: v1
kind: Service
metadata:
  name: alert-api-service
  labels:
    app.kubernetes.io/name: alert-api
    app.kubernetes.io/part-of: disaster-relief
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alert-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
