# Default values for frontend.
# This reflects the 'base' configuration.

replicaCount: 2

image:
  repository: acrdisasterreliefdev.azurecr.io/frontend
  pullPolicy: IfNotPresent
  # Overridden in environment values
  tag: "stable"

service:
  enabled: true
  type: ClusterIP
  port: 8080
  externalPort: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 15

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 3
  periodSeconds: 10

ingress:
  enabled: true
  className: azure-application-gateway
  annotations: {}
    # kubernetes.io/ingress.class: azure/application-gateway
  hosts:
    - host: disaster-relief.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: disaster-relief-tls
      hosts:
        - disaster-relief.com

partOf: disaster-relief
