apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-server-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: disaster-relief
spec:
  project: default

  source:
    repoURL: https://github.com/ciphernerd11/gitops-aks-microservices.git
    targetRevision: main
    path: kube/argocd-server/

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
